(function () {
  const modelOptions = ["P1-20260311", "v3.1-20260211", "v3.0-20250812", "v2.5-20250123"].map((value) => ({ label: value, value }));
  const textureQualityOptions = ["standard", "detailed", "extreme"].map((value) => ({ label: value, value }));
  const imgModels = ["seedream_v5", "seedream_v4"].map((value) => ({ label: value, value }));
  const templates = ["", "asset_extraction", "character_completion", "t_pose", "head_extraction", "3d_enhance", "variants", "print_clay", "figure"].map((value) => ({ label: value || "None", value }));
  const options = (values) => values.map((value) => ({ label: value, value }));
  const isP = (form) => String(form.model || "").startsWith("P1");
  const notP = (form) => !isP(form);
  const textureVisible = (form) => !isP(form) || form.texture === true;
  const source = (label = "Input source") => ({ name: "input", label, kind: "text", placeholder: "file_token, task_id, or https:// URL" });
  const common = [
    { name: "model", label: "Model", kind: "select", def: "P1-20260311", options: modelOptions },
    { name: "face_limit", label: "Face limit", kind: "number", def: 5000, min: 48, max: 200000, step: 100 },
    { name: "texture", label: "Texture", kind: "boolean", def: false },
    { name: "pbr", label: "PBR", kind: "boolean", def: false, show: textureVisible },
    { name: "model_seed", label: "Model seed", kind: "number", placeholder: "Random" },
    { name: "texture_seed", label: "Texture seed", kind: "number", placeholder: "Random", show: textureVisible },
    { name: "texture_quality", label: "Texture quality", kind: "select", def: "standard", options: textureQualityOptions, show: textureVisible },
    { name: "geometry_quality", label: "Geometry quality", kind: "select", def: "standard", options: options(["standard", "detailed"]), show: notP },
    { name: "auto_size", label: "Auto size", kind: "boolean", def: false, show: notP },
    { name: "quad", label: "Quad mesh", kind: "boolean", def: false, show: notP },
    { name: "smart_low_poly", label: "Smart low poly", kind: "boolean", def: false, show: notP },
    { name: "generate_parts", label: "Generate parts", kind: "boolean", def: false, show: notP },
    { name: "compress", label: "Compression", kind: "select", def: "", options: [{ label: "None", value: "" }, { label: "Geometry meshopt", value: "geometry" }], show: notP },
    { name: "export_uv", label: "Export UV", kind: "boolean", def: true, show: textureVisible }
  ];
  const ops = [
    { id: "text-to-model", group: "generate", label: "Text to Model", endpoint: "/tripo/generation/text-to-model", desc: "Prompt to textured 3D asset", icon: "type", output: "model", upload: "none", fields: [{ name: "prompt", label: "Prompt", kind: "textarea", def: "white anime hair accessory for a Roblox R6 avatar" }, { name: "negative_prompt", label: "Negative prompt", kind: "textarea", show: notP }, { name: "image_seed", label: "Image seed", kind: "number", placeholder: "Random", show: notP }, ...common] },
    { id: "image-to-model", group: "generate", label: "Image to Model", endpoint: "/tripo/generation/image-to-model", desc: "Single image to 3D asset", icon: "image-plus", output: "model", upload: "image", fields: [source("Image input"), { name: "enable_image_autofix", label: "Image autofix", kind: "boolean", def: true, show: notP }, { name: "texture_alignment", label: "Texture alignment", kind: "select", def: "original_image", options: [{ label: "Original image", value: "original_image" }, { label: "Geometry", value: "geometry" }], show: textureVisible }, ...common] },
    { id: "multiview-to-model", group: "generate", label: "Multiview to Model", endpoint: "/tripo/generation/multiview-to-model", desc: "Front, side, back images to 3D", icon: "grid-3x3", output: "model", upload: "multiview", fields: [{ name: "original_task_id", label: "Original multiview task", kind: "text" }, ...common] },
    { id: "image-to-splat", group: "generate", label: "Image to Splat", endpoint: "/tripo/generation/image-to-splat", desc: "Gaussian splat output", icon: "circle-dot", output: "splat", upload: "image", fields: [source("Image input")] },
    { id: "text-to-image", group: "image", label: "Text to Image", endpoint: "/tripo/generation/text-to-image", desc: "Prompt to image", icon: "sparkles", output: "image", upload: "none", fields: [{ name: "prompt", label: "Prompt", kind: "textarea", def: "front view of a Roblox UGC hair asset on a clean background" }, { name: "model", label: "Image model", kind: "select", def: "seedream_v4", options: imgModels }, { name: "template", label: "Template", kind: "select", def: "", options: templates }, { name: "t_pose", label: "T-pose", kind: "boolean", def: false }, { name: "sketch_to_render", label: "Sketch to render", kind: "boolean", def: false }] },
    { id: "image-to-image", group: "image", label: "Image to Image", endpoint: "/tripo/generation/image-to-image", desc: "Edit image with prompt/template", icon: "wand-2", output: "image", upload: "image", fields: [source("Primary image"), { name: "inputs_text", label: "Extra images", kind: "multiline", placeholder: "One URL/token per line" }, { name: "prompt", label: "Instruction", kind: "textarea" }, { name: "model", label: "Image model", kind: "select", def: "seedream_v5", options: imgModels }, { name: "template", label: "Template", kind: "select", def: "", options: templates }] },
    { id: "image-to-multiview", group: "image", label: "Image to Multiview", endpoint: "/tripo/generation/image-to-multiview", desc: "Single image to four views", icon: "split-square-horizontal", output: "multiview", upload: "image", fields: [source("Source image")] },
    { id: "edit-multiview", group: "image", label: "Edit Multiview", endpoint: "/tripo/generation/edit-multiview", desc: "Refine a multiview sheet", icon: "image", output: "multiview", upload: "image", fields: [source("Multiview image")] },
    { id: "skybox-generate", group: "skybox", label: "Create Skybox", endpoint: "/tripo/generation/text-to-image", desc: "6 images to live skybox", icon: "cloud-sun", output: "skybox", upload: "none", fields: [{ name: "prompt", label: "Skybox prompt", kind: "textarea", def: "soft Roblox lobby sky with warm clouds, clean horizon, bright studio lighting" }, { name: "model", label: "Image model", kind: "select", def: "seedream_v5", options: imgModels }, { name: "template", label: "Template", kind: "select", def: "", options: templates }] },
    { id: "texture", group: "models", label: "Texture", endpoint: "/tripo/models/texture", desc: "Retexture a model", icon: "palette", output: "model", upload: "model", fields: [source("Model input"), { name: "model", label: "Texture model", kind: "text" }, { name: "texture_seed", label: "Texture seed", kind: "number" }, { name: "texture_quality", label: "Texture quality", kind: "select", def: "standard", options: textureQualityOptions }, { name: "pbr", label: "PBR", kind: "boolean", def: true }] },
    { id: "import-model", group: "models", label: "Import Model", endpoint: "/tripo/models/import", desc: "Import uploaded model", icon: "file-box", output: "task", upload: "model", fields: [source("Model file")] },
    { id: "convert", group: "models", label: "Convert Format", endpoint: "/tripo/models/convert", desc: "Convert and optimize model output", icon: "file-archive", output: "model", upload: "model", fields: [source("Model input"), { name: "format", label: "Format", kind: "select", def: "GLTF", options: options(["GLTF", "USDZ", "FBX", "OBJ", "STL", "3MF"]) }, { name: "quad", label: "Quad remesh", kind: "boolean", def: false }, { name: "force_symmetry", label: "Force symmetry", kind: "boolean", def: false }, { name: "face_limit", label: "Face limit", kind: "number", def: 5000 }, { name: "texture_size", label: "Texture size", kind: "number", def: 2048 }, { name: "bake", label: "Bake textures", kind: "boolean", def: true }, { name: "pack_uv", label: "Pack UV", kind: "boolean", def: false }, { name: "scale_factor", label: "Scale factor", kind: "number", def: 1 }, { name: "with_animation", label: "With animation", kind: "boolean", def: true }, { name: "animate_in_place", label: "Animate in place", kind: "boolean", def: false }, { name: "part_names_text", label: "Part names", kind: "multiline" }] },
    { id: "segment", group: "mesh", label: "Segmentation", endpoint: "/tripo/mesh/segment", desc: "Split model into parts", icon: "layers-3", output: "json", upload: "model", fields: [source("Model input"), { name: "model", label: "Segmentation model", kind: "text" }] },
    { id: "complete", group: "mesh", label: "Mesh Complete", endpoint: "/tripo/mesh/complete", desc: "Complete segmented parts", icon: "boxes", output: "model", upload: "none", fields: [source("Segment task"), { name: "model", label: "Completion model", kind: "text" }, { name: "part_names_text", label: "Part names", kind: "multiline" }] },
    { id: "decimate", group: "mesh", label: "Retopology", endpoint: "/tripo/mesh/decimate", desc: "High poly to low poly", icon: "scissors", output: "model", upload: "model", fields: [source("Model input"), { name: "model", label: "Decimation model", kind: "text" }, { name: "face_limit", label: "Face limit", kind: "number", def: 5000 }, { name: "quad", label: "Quad mesh", kind: "boolean", def: false }, { name: "part_names_text", label: "Part names", kind: "multiline" }, { name: "bake", label: "Bake textures", kind: "boolean", def: true }] },
    { id: "rig-check", group: "animation", label: "Rig Check", endpoint: "/tripo/animations/rig-check", desc: "Check recommended rig", icon: "shield-check", output: "json", upload: "model", fields: [source("Model input")] },
    { id: "rig", group: "animation", label: "Auto Rig", endpoint: "/tripo/animations/rig", desc: "Add skeleton rig", icon: "activity", output: "model", upload: "model", fields: [source("Model input"), { name: "model", label: "Rig model", kind: "select", def: "rig-v2.0", options: options(["rig-v2.0", "rig-v1.0"]) }, { name: "rig_type", label: "Rig type", kind: "select", def: "biped", options: options(["biped", "quadruped", "hexapod", "octopod", "avian", "serpentine", "aquatic"]) }, { name: "spec", label: "Spec", kind: "select", def: "mixamo", options: options(["mixamo", "tripo"]) }, { name: "out_format", label: "Output format", kind: "select", def: "glb", options: ["glb", "fbx"].map((value) => ({ label: value.toUpperCase(), value })) }] },
    { id: "retarget", group: "animation", label: "Retarget", endpoint: "/tripo/animations/retarget", desc: "Apply preset animations", icon: "play", output: "model", upload: "none", fields: [source("Rigged task"), { name: "animation_mode", label: "Animation mode", kind: "select", def: "single", options: [{ label: "Single", value: "single" }, { label: "Multiple", value: "multiple" }] }, { name: "animation", label: "Animation", kind: "text", def: "preset:walk", show: (form) => form.animation_mode !== "multiple" }, { name: "animations_text", label: "Animations", kind: "multiline", def: "preset:walk\npreset:idle\npreset:run", show: (form) => form.animation_mode === "multiple" }, { name: "out_format", label: "Output format", kind: "select", def: "glb", options: ["glb", "fbx"].map((value) => ({ label: value.toUpperCase(), value })) }, { name: "bake_animation", label: "Bake animation", kind: "boolean", def: true }, { name: "export_with_geometry", label: "Export geometry", kind: "boolean", def: true }, { name: "animate_in_place", label: "In-place", kind: "boolean", def: false }] },
    { id: "hymotion-rbxm", group: "hymotion", label: "Text to Mixamo", endpoint: "/hymotion/generate", desc: "HY-Motion to Mixamo/Roblox animation", icon: "activity", output: "model", upload: "none", fields: [{ name: "prompt", label: "Motion prompt", kind: "textarea", def: "a Roblox character waves hello" }, { name: "format", label: "Output format", kind: "select", def: "glb", options: [{ label: "Mixamo GLB", value: "glb" }, { label: "Mixamo FBX", value: "fbx" }, { label: "Mixamo BVH", value: "bvh" }, { label: "Roblox RBXMX", value: "rbxmx" }, { label: "Roblox RBXM", value: "rbxm" }, { label: "glTF", value: "gltf" }] }, { name: "duration", label: "Duration", kind: "number", def: 3, min: 0.5, max: 12, step: 0.5 }, { name: "cfg_scale", label: "CFG scale", kind: "number", def: 5, min: 1, max: 10, step: 0.1 }, { name: "seed", label: "Seed", kind: "number" }, { name: "zero_root_xz", label: "In-place root", kind: "boolean", def: true }, { name: "loop", label: "Loop", kind: "boolean", def: false }, { name: "scale", label: "Position scale", kind: "number", def: 1 }] },
    { id: "opencloud-tripo-output", group: "opencloud", label: "Upload Tripo Output", endpoint: "/roblox/assets/models", desc: "Send latest Tripo model to Roblox Open Cloud", icon: "upload", output: "json", upload: "none", fields: [{ name: "modelUrl", label: "Tripo model URL", kind: "text", placeholder: "Leave blank to use latest output link" }, { name: "displayName", label: "Display name", kind: "text", def: "Tripo Generated Model" }, { name: "description", label: "Description", kind: "textarea", def: "Uploaded from Tripo output in Freed." }, { name: "dryRun", label: "Dry run", kind: "boolean", def: false }] },
    { id: "roblox-ugc-validator", group: "roblox", label: "Validate UGC", endpoint: "/roblox/avatar-validation/check", desc: "Roblox geometry rules", icon: "shield-check", output: "json", upload: "model", fields: [{ name: "assetType", label: "Asset type", kind: "select", def: "accessory", options: options(["accessory", "body_part", "layered_clothing", "model"]) }, { name: "rulesJson", label: "Studio rules JSON", kind: "textarea" }] },
    { id: "roblox-upload-model", group: "roblox", label: "Upload Model", endpoint: "/roblox/assets/models", desc: "Roblox Open Cloud upload", icon: "upload", output: "json", upload: "model", fields: [{ name: "displayName", label: "Display name", kind: "text", def: "Bloxlab Website Model" }, { name: "description", label: "Description", kind: "textarea", def: "Uploaded from Bloxlab website." }, { name: "dryRun", label: "Dry run", kind: "boolean", def: false }] },
    { id: "roblox-operation", group: "opencloud", label: "Upload Status", endpoint: "/roblox/assets/operations", desc: "Poll Roblox operation", icon: "badge-check", output: "json", upload: "none", fields: [{ name: "operationId", label: "Operation ID", kind: "text" }] },
    { id: "roblox-open-cloud", group: "opencloud", label: "Open Cloud Status", endpoint: "/roblox/open-cloud/status", desc: "Configured Roblox keys", icon: "shield-check", output: "json", upload: "none", fields: [] },
    { id: "task-query", group: "common", label: "Task Query", endpoint: "/tripo/tasks", desc: "Poll an existing task id", icon: "clipboard-list", output: "json", upload: "none", fields: [{ name: "task_id", label: "Task ID", kind: "text" }] },
    { id: "tripo-balance", group: "common", label: "Tripo Balance", endpoint: "/tripo/balance", desc: "Account balance", icon: "clipboard-list", output: "json", upload: "none", fields: [] },
    { id: "tripo-usage", group: "common", label: "Tripo Usage", endpoint: "/tripo/account/usage", desc: "Account usage", icon: "clipboard-list", output: "json", upload: "none", fields: [] }
  ];
  window.TRIPO_PANEL_DATA = {
    ops,
    groups: ["generate", "image", "skybox", "models", "mesh", "animation", "hymotion", "opencloud", "roblox", "common"],
    groupMeta: { generate: { label: "Model", icon: "cuboid" }, image: { label: "Image", icon: "image" }, skybox: { label: "Skybox", icon: "cloud-sun" }, models: { label: "Process", icon: "file-box" }, mesh: { label: "Mesh", icon: "layers-3" }, animation: { label: "Animate", icon: "play" }, hymotion: { label: "HyMotion", icon: "activity" }, opencloud: { label: "OpenCloud", icon: "upload" }, roblox: { label: "Roblox", icon: "shield-check" }, common: { label: "Task", icon: "clipboard-list" } },
    quickOpIds: ["image-to-model", "text-to-model", "multiview-to-model", "image-to-image"],
    topologyFieldNames: ["model", "face_limit", "texture", "pbr", "quad", "smart_low_poly", "geometry_quality", "texture_quality", "auto_size", "export_uv"],
    views: ["front", "left", "back", "right"],
    skyboxFaces: ["front", "back", "left", "right", "up", "down"],
    skyboxFaceLabel: { front: "front", back: "back", left: "left", right: "right", up: "top", down: "bottom" },
    modelExt: [".glb", ".gltf", ".fbx", ".obj", ".stl", ".3mf", ".usdz"],
    imageExt: [".png", ".jpg", ".jpeg", ".webp", ".gif"],
    fileExt: [".glb", ".gltf", ".fbx", ".obj", ".stl", ".3mf", ".usdz", ".rbxm", ".rbxmx", ".bvh", ".zip"],
    defaultApiRoot: "https://tripo-cloudflare-api.harrynguyenvoicespace.workers.dev/v1"
  };
})();